[package]
name = "build_ql_chksum"
version = "0.1.0"
authors = ["Pheenoh"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder = "1.3.2"
clap = "2.29"